[book]
authors = ["Michael Busbee"]
language = "en"
src = "src"
title = "techbook"

[output.html]
additional-css = ["theme/toc.css"]
additional-js = ["theme/toc.js"]
favicon = "favicon.ico"

[output.html.fold]
enable = true
level = 0
