[book]
authors = ["Michael Busbee"]
language = "en"
src = "src"
title = "busbeetech.com"

[output.html]
additional-css = ["theme/toc.css", "theme/nav.css"]
additional-js = ["theme/toc.js", "theme/sidebar.js", "theme/print.js"]

[output.html.print]
enable = false

[output.html.fold]
enable = true
level = 0
